# Generated by Selenium IDE
import os  # <--- Fondamentale per i percorsi
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestAggiungiServizioOfferto:
    def setup_method(self):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self):
        self.driver.quit()

    def test_aggiungiServizioOfferto(self):
        self.driver.get("http://127.0.0.1:5000/fornitori")
        self.driver.set_window_size(2576, 1416)

        self.driver.find_element(By.ID, "modal-buttonAF").click()
        self.driver.find_element(By.ID, "description").click()
        self.driver.find_element(By.ID, "description").send_keys("Sala Maggiore")
        self.driver.find_element(By.ID, "price").click()
        self.driver.find_element(By.ID, "price").send_keys("250")


        # --- RISOLUZIONE ISSUE:  SVG ---
        # 1 cartella dove si trova questo file di test
        current_test_dir = os.path.dirname(os.path.abspath(__file__))

        # 2. Risali alla cartella principale del progetto
        project_root = os.path.dirname(current_test_dir)

        # 3.  il percorso immagine
        image_path = os.path.join(project_root, "BEvent_app", "static", "images", "trullo.svg")

        # 4. Invia il file SVG (Formato Green-Compliant)
        self.driver.find_element(By.ID, "fileInput").send_keys(image_path)
        # -------------------------------------------------------

        self.driver.find_element(By.CSS_SELECTOR, "form > .modalButtonAF").click()